default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pavithra
  password: 123456789
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_dev

